## 예외 계층도

![image-20240124212601238](https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20240124212601.png)



## 체크 예외

- Exception을 상속받은 예외는 체크예외가 됨
- 체크예외: 사용되는 곳에서 반드시 catch하거나 throw 해줘야 함 (안하면 컴파일 에러)



**throw된 예외에 대한 test code 작성하기**

```java
@Test
voic check_thrown_error_is_MyCheckedException() {
	Service service = new Service();
	Assertions.assertThatThrownBy(() -> service.callThrow())
		.isInstanceOf(MyCheckedException.class);
}
```

 

**예외가 오류 메시지를 보관하도록 하기**

- Exception의 생성자중 String을 인자로 받는 생성자를 통해 보관



**던질 예외의 구체적 지정**

Exception이 부모 클래스이기 때문에 throws Exception을 사용해도 컴파일이 가능하지만, 이는 모든 Exception을 던질 수 있도록 열려있기 때문에 어떤 예외가 처리되는지 알기 어렵다.

따라서 지양해야하는 코드



**체크 예외의 장단점**

장점: 실수로 예외 처리를 누락하지 않도록 컴파일 타임에 잡아줌

단점: 굳이 잡아서 처리하지 않아도 되는 예외임에도 모두 챙겨야 함

(수많은 라이브러리들이 던지는 예외들을 잡아서 처리해야 함)



## 언체크 예외

- RumtimeException과 그 자식 예외들을 언체크 예외로 분류
- 체크 예외와 다른점은 throws를 붙이지 않아도 컴파일이 된다는 점
  - 이 경우에는 예외를 자동으로 던짐



**언체크 예외에 throws를 명시하는 경우**

- 개발자로 하여금 이러한 Exception이 발생한다는 것을 인지하게 할 수 있음



## 체크 예외 활용

**언제 체크 예외를 쓰고 언제 런타임 익셉션을 쓸까?**

- 기본적으로 언체크 예외를 사용
- 체크 예외는 비즈니스 로직상 의도적으로 던지는 예외에 사용
  - 개발자가 처리해줘야하는 예외



**체크 예외의 문제점**

예외를 잡거나 처리해야하는 체크 예외를 전달받은 서비스 계층

하지만 서비스 계층도 이 예외들을 처리할 능력이 없다

따라서 서비스를 호출하는 컨트롤러에게 예외를 throw하게 된다.

하지만 컨트롤러도 이를 처리하지 못해 또다시 throw하게 되고

결국 서블릿에 의해 오류 페이지가 나오게 된다.

이처럼 컴파일을 위해 어쩔 수 없이 던진 예외를 아무도 처리하지 못해 발생하는 문제가 발생한다.

사용자에게 전달될 필요가 없는 수준의 오류를 전달하게 되는 문제

 

체크 예외의 문제점 정리

- 복구 불가능한 예외
  - 예외 발생 사실을 안다해서 이를 복구하는 것은 불가능
    - 따라서 이런 예외들은 오류 로그만 남기고 공통적으로 처리해야 함
    - 스프링의 `ControllerAdvice`을 사용하면 깔끔하게 공통처리가 가능
- 의존관계에 대한 문제
  - SQLException, ConnectException 등의 어떠한 기술(JDBC)의 예외를 그대로 던지는 것은 이 기술에 의존하는 것이나 마찬가지
    - 만약 기술을 바꾸게 되면 이 예외의 의존성 때문에 코드를 모두 수정해야 함



**throws Exception**

여러개의 체크 예외를 한번에 묶어서 throw할 수 있는 코드긴 하나

무시하고 싶은 예외뿐만 아니라 다루려고 의도했던 체크 예외까지 묶어서 처리되어버리므로 이를 처리할 수 없어 안티패턴



## 언체크 예외의 활용

**체크 예외를 잡아서 언체크 예외로 내보내기**

```java
static class RuntimeSQLException extends RuntimeException {
	public RuntimeSQLException(String msg) {
		super(msg);
	}
}

public void call() {
	try {
	} catch (SQLException e) {
		throw new RuntimeSQLException();
	}
}
```

- 체크 예외를 잡아서 런타임 예외로 바꾸는 코드
- 서비스 계층이 예외에 의해 특정 기술에 의존성을 가지는 것을 방지할 수 있음



![image-20240124210641671](https://raw.githubusercontent.com/Neph3779/Blog-Image/forUpload/img/20240124210647.png)



기술이 변경돼도 예외를 공통적으로 처리하는 곳에서만 이를 처리해주면 됨



**체크 예외에 대한 이야기**

과거에는 체크 예외가 항상 더 나은 선택이라 생각했음

하지만 시간이 흐르면서 복구 불가능한 예외가 너무 많아졌음

매번 throws를 붙여가면서 예외를 모두 처리해줘야하는 문제가 생기다보니

최근 라이브러리들은 기본적으로 런타임 예외를 기본으로 사용

런타임 예외는 잡아서 처리할지 말지를 개발자가 결정할 수 있기 때문에 더 유연함

(컴파일 단에서 체크할 수 있다는 이점을 포기)

하지만 이런 런타임 예외는 놓치고 넘어갈 수 있기 때문에 "문서화"가 아주 중요함

혹은 throws SomeRuntimeException 처럼 코드상에 이를 남겨두어야 함



**문서화 예시 (JPA EntityManager)**

```java
/**
 * Make an instance managed and persistent.
 * @param entity entity instance
 * @throws EntityExistsException if the instance is not an entity
 * @throws TransactionRequiredException if there is no transaction when invoked on a container-managed entity manager of that is of type <code>PersistenceContextType.TRANSACTION</code>
*/
public void persist(Object entity);
```



## 예외 포함과 스택 트레이스 (중요)

**예외를 전환할때는 꼭 기존 예외를 포함해야 한다**

그렇지 않으면 stack trace 확인시 문제 발생



```java
static class RuntimeSQLException extends RuntimeException {
	public RuntimeSQLException(Throwable cause) {
		super(cause);
	}
}

public void call() {
	try {
	} catch (SQLException e) {
		throw new RuntimeSQLException(e);
	}
}
```

기존 exception을 새로운 exception을 생성할때 인자로 넣어주게되면

새로운 exception의 내부에 기존 exception을 저장할 수 있음



```java
void logEx() {
	try {
		controller.request();
	} catch (Exception e) {
		log.info("exception", e);
	}
}
```

exception을 log로 출력해보면 어떤 예외에 의해 발생한 것인지 그 구체적인 정보가 기록됨 

(감싸진 예외가 아닌 실제로 예외를 일으킨 예외가 기록됨)

만약 기존 예외를 포함하지 않는다면 어떤 예외에 의해 발생했는지 알 수 없음



## 정리

### 오늘 들은 강의

- **스프링 DB 1편 - 데이터 접근 핵심 원리 섹션 5** 
  - 체크 예외와 언체크 예외의 차이
  - 언체크 예외가 주류로 자리잡게된 배경
    - 체크 예외의 문제점들
  - 예외 전환시 기존 예외 전환의 필요성



### 오늘 읽은 글

- **[자바의 내부 클래스는 static으로 선언하자](https://inpa.tistory.com/entry/JAVA-%E2%98%95-%EC%9E%90%EB%B0%94%EC%9D%98-%EB%82%B4%EB%B6%80-%ED%81%B4%EB%9E%98%EC%8A%A4%EB%8A%94-static-%EC%9C%BC%EB%A1%9C-%EC%84%A0%EC%96%B8%ED%95%98%EC%9E%90)**
  - non-static 멤버 클래스의 인스턴스는 자신을 감싸고 있는 클래스의 인스턴스와 "암묵적으로" 연결됨
  - `Outer.this.getField()` 처럼 인스턴스를 사용할 수 있음
    - 이때 사용된 this를 정규화된 this라 부름
  - 이렇듯 내부 클래스가 외부 클래스를 참조하면 GC가 외부 클래스를 메모리에서 해제시키지 못하는 문제가 발생함
  - 내부 클래스를 static으로 선언한다면 이런 문제가 발생하지 않는다.
    - 이유: Outer class의 instance를 통하지 않고서도 그 자체로도 instance 생성이 가능하다. 
      - 외부 참조를 하지 않는다.

